2024-12-01 12:17:31.457 | ERROR    | Core.Graph.PassageGraph:_build_graph:70 - Error building graph: 'dict' object has no attribute 'content'
Traceback (most recent call last):

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2270, in <module>
    main()
    └ <function main at 0x72cf383a07c0>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2252, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 29781, 'vm_type': None, 'client': None, 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': False, 'mu...
              │        └ <function PyDB.run at 0x72cf3839b420>
              └ <__main__.PyDB object at 0x72cfca79e650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1563, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ '/home/yingli/GraphRAG/test_kgp.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x72cf3839b4c0>
           └ <__main__.PyDB object at 0x72cfca79e650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ '/home/yingli/GraphRAG/test_kgp.py'
    │             └ <function execfile at 0x72cf6f51e340>
    └ <module '_pydev_bundle.pydev_imports' from '/home/yingli/.pycharm_helpers/pydev/_pydev_bundle/pydev_imports.py'>

  File "/home/yingli/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ '/home/yingli/GraphRAG/test_kgp.py'
                 └ 'from typing import Union, Any\n\nimport tiktoken\n\nfrom Core.Chunk.ChunkFactory import get_chunks\nfrom Core.Common.Utils i...

  File "/home/yingli/GraphRAG/test_kgp.py", line 38, in <module>
    asyncio.run(graph.build_graph(ordered_chunks))
    │       │   │     │           └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', {'tokens': 1024, 'content': 'The Project Gutenberg eBook of A Christmas Carol\n  ...
    │       │   │     └ <function BaseGraph.build_graph at 0x72cf0f95f740>
    │       │   └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
    │       └ <function _patch_asyncio.<locals>.run at 0x72cf383c6d40>
    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           │    │                  └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
           │    └ <function _patch_loop.<locals>.run_until_complete at 0x72cf383c72e0>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
    │    └ <function _patch_loop.<locals>._run_once at 0x72cf383c7380>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x72cf57b69800>
    └ <Handle Task.__wakeup(<_GatheringFu...e 'content'")>)>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.__wakeup(<_GatheringFu...e 'content'")>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.__wakeup(<_GatheringFu...e 'content'")>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.__wakeup(<_GatheringFu...e 'content'")>)>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 352, in __wakeup
    self.__step(exc)
    │           └ AttributeError("'dict' object has no attribute 'content'")
    └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 394, in step
    step_orig(task, exc)
    │         │     └ AttributeError("'dict' object has no attribute 'content'")
    │         └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
    └ <function Task.__step at 0x72cf57bb5bc0>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 279, in __step
    result = coro.throw(exc)
             │    │     └ AttributeError("'dict' object has no attribute 'content'")
             │    └ <method 'throw' of 'coroutine' objects>
             └ <coroutine object BaseGraph.build_graph at 0x72cf11739490>

  File "/home/yingli/GraphRAG/Core/Graph/BaseGraph.py", line 52, in build_graph
    await self._build_graph(chunks)
          │    │            └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', {'tokens': 1024, 'content': 'The Project Gutenberg eBook of A Christmas Carol\n  ...
          │    └ <function PassageGraph._build_graph at 0x72cf0db3e520>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

> File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 65, in _build_graph
    results = await asyncio.gather(
                    │       └ <function gather at 0x72cf57bb6480>
                    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 349, in __wakeup
    future.result()
    │      └ <method 'result' of '_asyncio.Future' objects>
    └ <_GatheringFuture finished exception=AttributeError("'dict' object has no attribute 'content'")>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             │    └ <method 'send' of 'coroutine' objects>
             └ <coroutine object PassageGraph._extract_node_relationship at 0x72cf0e5fa7a0>

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 57, in _extract_node_relationship
    chunk_info = chunk_info.content
                 └ {'tokens': 1024, 'content': 'The Project Gutenberg eBook of A Christmas Carol\n    \nThis ebook is for the use of anyone anyw...

AttributeError: 'dict' object has no attribute 'content'
2024-12-01 12:17:31.501 | INFO     | Core.Graph.PassageGraph:_build_graph:72 - Constructing graph finished
2024-12-01 13:33:05.044 | ERROR    | Core.Graph.PassageGraph:_build_graph:70 - Error building graph: 'dict' object has no attribute 'content'
Traceback (most recent call last):

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2270, in <module>
    main()
    └ <function main at 0x709933f9c7c0>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2252, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 29781, 'vm_type': None, 'client': None, 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': False, 'mu...
              │        └ <function PyDB.run at 0x709933f9b420>
              └ <__main__.PyDB object at 0x7099c639e650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1563, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ '/home/yingli/GraphRAG/test_kgp.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x709933f9b4c0>
           └ <__main__.PyDB object at 0x7099c639e650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ '/home/yingli/GraphRAG/test_kgp.py'
    │             └ <function execfile at 0x70996b11e340>
    └ <module '_pydev_bundle.pydev_imports' from '/home/yingli/.pycharm_helpers/pydev/_pydev_bundle/pydev_imports.py'>

  File "/home/yingli/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ '/home/yingli/GraphRAG/test_kgp.py'
                 └ 'from typing import Union, Any\n\nimport tiktoken\n\nfrom Core.Chunk.ChunkFactory import get_chunks\nfrom Core.Common.Utils i...

  File "/home/yingli/GraphRAG/test_kgp.py", line 38, in <module>
    asyncio.run(graph.build_graph(ordered_chunks))
    │       │   │     │           └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', {'tokens': 1024, 'content': 'The Project Gutenberg eBook of A Christmas Carol\n  ...
    │       │   │     └ <function BaseGraph.build_graph at 0x70990af5f740>
    │       │   └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
    │       └ <function _patch_asyncio.<locals>.run at 0x709933fc6d40>
    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           │    │                  └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
           │    └ <function _patch_loop.<locals>.run_until_complete at 0x709933fc72e0>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
    │    └ <function _patch_loop.<locals>._run_once at 0x709933fc7380>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x709955769800>
    └ <Handle Task.__wakeup(<_GatheringFu...e 'content'")>)>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.__wakeup(<_GatheringFu...e 'content'")>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.__wakeup(<_GatheringFu...e 'content'")>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.__wakeup(<_GatheringFu...e 'content'")>)>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 352, in __wakeup
    self.__step(exc)
    │           └ AttributeError("'dict' object has no attribute 'content'")
    └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 394, in step
    step_orig(task, exc)
    │         │     └ AttributeError("'dict' object has no attribute 'content'")
    │         └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
    └ <function Task.__step at 0x7099557b5bc0>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 279, in __step
    result = coro.throw(exc)
             │    │     └ AttributeError("'dict' object has no attribute 'content'")
             │    └ <method 'throw' of 'coroutine' objects>
             └ <coroutine object BaseGraph.build_graph at 0x70990cd3dbe0>

  File "/home/yingli/GraphRAG/Core/Graph/BaseGraph.py", line 52, in build_graph
    await self._build_graph(chunks)
          │    │            └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', {'tokens': 1024, 'content': 'The Project Gutenberg eBook of A Christmas Carol\n  ...
          │    └ <function PassageGraph._build_graph at 0x70990913e520>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

> File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 65, in _build_graph
    results = await asyncio.gather(
                    │       └ <function gather at 0x7099557b6480>
                    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 349, in __wakeup
    future.result()
    │      └ <method 'result' of '_asyncio.Future' objects>
    └ <_GatheringFuture finished exception=AttributeError("'dict' object has no attribute 'content'")>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             │    └ <method 'send' of 'coroutine' objects>
             └ <coroutine object PassageGraph._extract_node_relationship at 0x709909bfa7a0>

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 57, in _extract_node_relationship
    chunk_info = chunk_info.content
                 └ {'tokens': 1024, 'content': 'The Project Gutenberg eBook of A Christmas Carol\n    \nThis ebook is for the use of anyone anyw...

AttributeError: 'dict' object has no attribute 'content'
2024-12-01 13:33:05.088 | INFO     | Core.Graph.PassageGraph:_build_graph:72 - Constructing graph finished
2024-12-01 13:36:33.415 | ERROR    | Core.Graph.PassageGraph:_build_graph:70 - Error building graph: 'WATAnnotation' object has no attribute 'prior_prob'
Traceback (most recent call last):

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           │    │                  └ <Task cancelling name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
           │    └ <function _patch_loop.<locals>.run_until_complete at 0x7b5636bd72e0>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
    │    └ <function _patch_loop.<locals>._run_once at 0x7b5636bd7380>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7b5658375800>
    └ <Handle _patch_task.<locals>.step()>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle _patch_task.<locals>.step()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle _patch_task.<locals>.step()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle _patch_task.<locals>.step()>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 394, in step
    step_orig(task, exc)
    │         │     └ None
    │         └ <Task finished name='Task-8' coro=<PassageGraph._extract_node_relationship() done, defined at /home/yingli/GraphRAG/Core/Grap...
    └ <function Task.__step at 0x7b56583c5bc0>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             │    └ <method 'send' of 'coroutine' objects>
             └ <coroutine object PassageGraph._extract_node_relationship at 0x7b560bd07100>

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 60, in _extract_node_relationship
    wat_annotations = await self._wat_entity_linking(chunk_info)
                            │    │                   └ "handed the\ncredentials back.\n\n'At this festive season of the year, Mr. Scrooge,' said the gentleman,\ntaking up a pen, 'i...
                            │    └ <staticmethod(<function PassageGraph._wat_entity_linking at 0x7b5630d0dc60>)>
                            └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 47, in _wat_entity_linking
    response = requests.get(wat_url, params=payload)
               │        │   │               └ [('gcube-token', '07e1bd33-c0f5-41b0-979b-4c9a859eec3f-843339462'), ('text', "handed the\ncredentials back.\n\n'At this festi...
               │        │   └ 'https://wat.d4science.org/wat/tag/tag'
               │        └ <function get at 0x7b560bd09620>
               └ <module 'requests' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/site-packages/requests/__init__.py'>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           │              │           │         └ {}
           │              │           └ [('gcube-token', '07e1bd33-c0f5-41b0-979b-4c9a859eec3f-843339462'), ('text', "handed the\ncredentials back.\n\n'At this festi...
           │              └ 'https://wat.d4science.org/wat/tag/tag'
           └ <function request at 0x7b560bd094e0>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': [('gcube-token', '07e1bd33-c0f5-41b0-979b-4c9a859eec3f-843339462'), ('text', "handed the\ncredentials back.\n\n'At...
           │       │              │           └ 'https://wat.d4science.org/wat/tag/tag'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7b560bd4d9e0>
           └ <requests.sessions.Session object at 0x7b560aff2d10>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': None, 'allow_redirects': True, 'proxies': OrderedDict(), 'stream': False, 'verify': True, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7b560bd4dee0>
           └ <requests.sessions.Session object at 0x7b560aff2d10>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/site-packages/requests/sessions.py", line 746, in send
    r.content
    │ └ <property object at 0x7b560bd38130>
    └ <Response [200]>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
    │    │                   │    │            └ 10240
    │    │                   │    └ <function Response.iter_content at 0x7b560bd31ee0>
    │    │                   └ <Response [200]>
    │    └ False
    └ <Response [200]>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
               │    │   │      └ 10240
               │    │   └ <function HTTPResponse.stream at 0x7b560d16ccc0>
               │    └ <urllib3.response.HTTPResponse object at 0x7b5608a3f0d0>
               └ <Response [200]>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/site-packages/urllib3/response.py", line 1057, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
               │    │            │                   └ True
               │    │            └ 10240
               │    └ <function HTTPResponse.read_chunked at 0x7b560d16d260>
               └ <urllib3.response.HTTPResponse object at 0x7b5608a3f0d0>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/site-packages/urllib3/response.py", line 1209, in read_chunked
    chunk = self._handle_chunk(amt)
            │    │             └ 10240
            │    └ <function HTTPResponse._handle_chunk at 0x7b560d16d1c0>
            └ <urllib3.response.HTTPResponse object at 0x7b5608a3f0d0>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/site-packages/urllib3/response.py", line 1146, in _handle_chunk
    value = self._fp._safe_read(amt)  # type: ignore[union-attr]
            │    │   │          └ 10240
            │    │   └ <function HTTPResponse._safe_read at 0x7b5670724a40>
            │    └ <http.client.HTTPResponse object at 0x7b5608a3f070>
            └ <urllib3.response.HTTPResponse object at 0x7b5608a3f0d0>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/http/client.py", line 638, in _safe_read
    data = self.fp.read(amt)
           │    │       └ 10240
           │    └ None
           └ <http.client.HTTPResponse object at 0x7b5608a3f070>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/socket.py", line 718, in readinto
    return self._sock.recv_into(b)
           │    │               └ <memory at 0x7b560c7edfc0>
           │    └ None
           └ <socket.SocketIO object at 0x7b5608a3f4f0>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/ssl.py", line 1314, in recv_into
    return self.read(nbytes, buffer)
           │    │    │       └ <memory at 0x7b560c7edfc0>
           │    │    └ 8192
           │    └ <function SSLSocket.read at 0x7b56707ae020>
           └ <ssl.SSLSocket [closed] fd=-1, family=2, type=1, proto=6>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/ssl.py", line 1166, in read
    return self._sslobj.read(len, buffer)
           │    │            │    └ <memory at 0x7b560c7edfc0>
           │    │            └ 8192
           │    └ None
           └ <ssl.SSLSocket [closed] fd=-1, family=2, type=1, proto=6>

KeyboardInterrupt


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2270, in <module>
    main()
    └ <function main at 0x7b5636bb07c0>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2252, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 29781, 'vm_type': None, 'client': None, 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': False, 'mu...
              │        └ <function PyDB.run at 0x7b5636bab420>
              └ <__main__.PyDB object at 0x7b564e5d8910>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1563, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ '/home/yingli/GraphRAG/test_kgp.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x7b5636bab4c0>
           └ <__main__.PyDB object at 0x7b564e5d8910>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ '/home/yingli/GraphRAG/test_kgp.py'
    │             └ <function execfile at 0x7b566dd2a340>
    └ <module '_pydev_bundle.pydev_imports' from '/home/yingli/.pycharm_helpers/pydev/_pydev_bundle/pydev_imports.py'>

  File "/home/yingli/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ '/home/yingli/GraphRAG/test_kgp.py'
                 └ 'from typing import Union, Any\n\nimport tiktoken\n\nfrom Core.Chunk.ChunkFactory import get_chunks\nfrom Core.Common.Utils i...

  File "/home/yingli/GraphRAG/test_kgp.py", line 38, in <module>
    asyncio.run(graph.build_graph(ordered_chunks))
    │       │   │     │           └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
    │       │   │     └ <function BaseGraph.build_graph at 0x7b560db6fa60>
    │       │   └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
    │       └ <function _patch_asyncio.<locals>.run at 0x7b5636bd6d40>
    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 143, in run
    loop.run_until_complete(task)
    │    │                  └ <Task cancelling name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
    │    └ <function _patch_loop.<locals>.run_until_complete at 0x7b5636bd72e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
    │    └ <function _patch_loop.<locals>._run_once at 0x7b5636bd7380>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7b5658375800>
    └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 352, in __wakeup
    self.__step(exc)
    │           └ AttributeError("'WATAnnotation' object has no attribute 'prior_prob'")
    └ <Task cancelling name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 394, in step
    step_orig(task, exc)
    │         │     └ AttributeError("'WATAnnotation' object has no attribute 'prior_prob'")
    │         └ <Task cancelling name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
    └ <function Task.__step at 0x7b56583c5bc0>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 279, in __step
    result = coro.throw(exc)
             │    │     └ AttributeError("'WATAnnotation' object has no attribute 'prior_prob'")
             │    └ <method 'throw' of 'coroutine' objects>
             └ <coroutine object BaseGraph.build_graph at 0x7b560f94c790>

  File "/home/yingli/GraphRAG/Core/Graph/BaseGraph.py", line 52, in build_graph
    await self._build_graph(chunks)
          │    │            └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
          │    └ <function PassageGraph._build_graph at 0x7b560bd4e840>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

> File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 65, in _build_graph
    results = await asyncio.gather(
                    │       └ <function gather at 0x7b56583c6480>
                    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 349, in __wakeup
    future.result()
    │      └ <method 'result' of '_asyncio.Future' objects>
    └ <_GatheringFuture finished exception=AttributeError("'WATAnnotation' object has no attribute 'prior_prob'")>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             │    └ <method 'send' of 'coroutine' objects>
             └ <coroutine object PassageGraph._extract_node_relationship at 0x7b560bd07c40>

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 61, in _extract_node_relationship
    return await self._build_graph_from_wat(wat_annotations, chunk_key)
                 │    │                     │                └ 'chunk-d5cb63c91e4bea751bf090388c7859e9'
                 │    │                     └ [WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAn...
                 │    └ <function PassageGraph._build_graph_from_wat at 0x7b560bd4eb60>
                 └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 103, in _build_graph_from_wat
    if wiki.wiki_title != '' and wiki.prior_prob > self.config.prior_prob:
       │    │                    │                 │    └ Config(extra_fields=None, project_path='', project_name='', inc=False, reqa_file='', max_auto_summarize_code=0, git_reinit=Fa...
       │    │                    │                 └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
       │    │                    └ WATAnnotation()
       │    └ 'Project_Gutenberg'
       └ WATAnnotation()

AttributeError: 'WATAnnotation' object has no attribute 'prior_prob'
2024-12-01 13:36:33.538 | INFO     | Core.Graph.PassageGraph:_build_graph:72 - Constructing graph finished
2024-12-01 13:37:18.898 | ERROR    | Core.Graph.PassageGraph:_build_graph:70 - Error building graph: 'WATAnnotation' object has no attribute 'prior_prob'
Traceback (most recent call last):

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2270, in <module>
    main()
    └ <function main at 0x711c4a9ac7c0>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2252, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 29781, 'vm_type': None, 'client': None, 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': False, 'mu...
              │        └ <function PyDB.run at 0x711c4a9ab420>
              └ <__main__.PyDB object at 0x711cdb19e650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1563, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ '/home/yingli/GraphRAG/test_kgp.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x711c4a9ab4c0>
           └ <__main__.PyDB object at 0x711cdb19e650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ '/home/yingli/GraphRAG/test_kgp.py'
    │             └ <function execfile at 0x711c81b2a340>
    └ <module '_pydev_bundle.pydev_imports' from '/home/yingli/.pycharm_helpers/pydev/_pydev_bundle/pydev_imports.py'>

  File "/home/yingli/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ '/home/yingli/GraphRAG/test_kgp.py'
                 └ 'from typing import Union, Any\n\nimport tiktoken\n\nfrom Core.Chunk.ChunkFactory import get_chunks\nfrom Core.Common.Utils i...

  File "/home/yingli/GraphRAG/test_kgp.py", line 38, in <module>
    asyncio.run(graph.build_graph(ordered_chunks))
    │       │   │     │           └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
    │       │   │     └ <function BaseGraph.build_graph at 0x711c1f96fa60>
    │       │   └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
    │       └ <function _patch_asyncio.<locals>.run at 0x711c4a9d6d40>
    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           │    │                  └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
           │    └ <function _patch_loop.<locals>.run_until_complete at 0x711c4a9d72e0>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
    │    └ <function _patch_loop.<locals>._run_once at 0x711c4a9d7380>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x711c6a179800>
    └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 352, in __wakeup
    self.__step(exc)
    │           └ AttributeError("'WATAnnotation' object has no attribute 'prior_prob'")
    └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 394, in step
    step_orig(task, exc)
    │         │     └ AttributeError("'WATAnnotation' object has no attribute 'prior_prob'")
    │         └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
    └ <function Task.__step at 0x711c6a1c5bc0>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 279, in __step
    result = coro.throw(exc)
             │    │     └ AttributeError("'WATAnnotation' object has no attribute 'prior_prob'")
             │    └ <method 'throw' of 'coroutine' objects>
             └ <coroutine object BaseGraph.build_graph at 0x711c28128d40>

  File "/home/yingli/GraphRAG/Core/Graph/BaseGraph.py", line 52, in build_graph
    await self._build_graph(chunks)
          │    │            └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
          │    └ <function PassageGraph._build_graph at 0x711c1db4e840>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

> File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 65, in _build_graph
    results = await asyncio.gather(
                    │       └ <function gather at 0x711c6a1c6480>
                    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 349, in __wakeup
    future.result()
    │      └ <method 'result' of '_asyncio.Future' objects>
    └ <_GatheringFuture finished exception=AttributeError("'WATAnnotation' object has no attribute 'prior_prob'")>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             │    └ <method 'send' of 'coroutine' objects>
             └ <coroutine object PassageGraph._extract_node_relationship at 0x711c1db07c40>

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 61, in _extract_node_relationship
    return await self._build_graph_from_wat(wat_annotations, chunk_key)
                 │    │                     │                └ 'chunk-d5cb63c91e4bea751bf090388c7859e9'
                 │    │                     └ [WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAn...
                 │    └ <function PassageGraph._build_graph_from_wat at 0x711c1db4eb60>
                 └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 103, in _build_graph_from_wat
    if wiki.wiki_title != '' and wiki.prior_prob > self.config.prior_prob:
       │    │                    │                 │    └ Config(extra_fields=None, project_path='', project_name='', inc=False, reqa_file='', max_auto_summarize_code=0, git_reinit=Fa...
       │    │                    │                 └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
       │    │                    └ WATAnnotation()
       │    └ 'Project_Gutenberg'
       └ WATAnnotation()

AttributeError: 'WATAnnotation' object has no attribute 'prior_prob'
2024-12-01 13:37:18.938 | INFO     | Core.Graph.PassageGraph:_build_graph:72 - Constructing graph finished
2024-12-01 13:38:41.677 | ERROR    | Core.Graph.PassageGraph:_build_graph:70 - Error building graph: 'WATAnnotation' object has no attribute 'prior_prob'
Traceback (most recent call last):

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2270, in <module>
    main()
    └ <function main at 0x7c7d9e3b07c0>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2252, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 29781, 'vm_type': None, 'client': None, 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': False, 'mu...
              │        └ <function PyDB.run at 0x7c7d9e3af420>
              └ <__main__.PyDB object at 0x7c7e2e19e650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1563, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ '/home/yingli/GraphRAG/test_kgp.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x7c7d9e3af4c0>
           └ <__main__.PyDB object at 0x7c7e2e19e650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ '/home/yingli/GraphRAG/test_kgp.py'
    │             └ <function execfile at 0x7c7dd552e340>
    └ <module '_pydev_bundle.pydev_imports' from '/home/yingli/.pycharm_helpers/pydev/_pydev_bundle/pydev_imports.py'>

  File "/home/yingli/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ '/home/yingli/GraphRAG/test_kgp.py'
                 └ 'from typing import Union, Any\n\nimport tiktoken\n\nfrom Core.Chunk.ChunkFactory import get_chunks\nfrom Core.Common.Utils i...

  File "/home/yingli/GraphRAG/test_kgp.py", line 38, in <module>
    asyncio.run(graph.build_graph(ordered_chunks))
    │       │   │     │           └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
    │       │   │     └ <function BaseGraph.build_graph at 0x7c7d73973a60>
    │       │   └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
    │       └ <function _patch_asyncio.<locals>.run at 0x7c7d9e3dad40>
    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           │    │                  └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
           │    └ <function _patch_loop.<locals>.run_until_complete at 0x7c7d9e3db2e0>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
    │    └ <function _patch_loop.<locals>._run_once at 0x7c7d9e3db380>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7c7dbfb7d800>
    └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 352, in __wakeup
    self.__step(exc)
    │           └ AttributeError("'WATAnnotation' object has no attribute 'prior_prob'")
    └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 394, in step
    step_orig(task, exc)
    │         │     └ AttributeError("'WATAnnotation' object has no attribute 'prior_prob'")
    │         └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
    └ <function Task.__step at 0x7c7dbfbc9bc0>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 279, in __step
    result = coro.throw(exc)
             │    │     └ AttributeError("'WATAnnotation' object has no attribute 'prior_prob'")
             │    └ <method 'throw' of 'coroutine' objects>
             └ <coroutine object BaseGraph.build_graph at 0x7c7d74dbb030>

  File "/home/yingli/GraphRAG/Core/Graph/BaseGraph.py", line 52, in build_graph
    await self._build_graph(chunks)
          │    │            └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
          │    └ <function PassageGraph._build_graph at 0x7c7d71b52840>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

> File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 65, in _build_graph
    results = await asyncio.gather(
                    │       └ <function gather at 0x7c7dbfbca480>
                    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 349, in __wakeup
    future.result()
    │      └ <method 'result' of '_asyncio.Future' objects>
    └ <_GatheringFuture finished exception=AttributeError("'WATAnnotation' object has no attribute 'prior_prob'")>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             │    └ <method 'send' of 'coroutine' objects>
             └ <coroutine object PassageGraph._extract_node_relationship at 0x7c7d71b0bc40>

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 61, in _extract_node_relationship
    return await self._build_graph_from_wat(wat_annotations, chunk_key)
                 │    │                     │                └ 'chunk-d5cb63c91e4bea751bf090388c7859e9'
                 │    │                     └ [WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAn...
                 │    └ <function PassageGraph._build_graph_from_wat at 0x7c7d71b52b60>
                 └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 103, in _build_graph_from_wat
    if wiki.wiki_title != '' and wiki.prior_prob > self.config.prior_prob:
       │    │                    │                 │    └ Config(extra_fields=None, project_path='', project_name='', inc=False, reqa_file='', max_auto_summarize_code=0, git_reinit=Fa...
       │    │                    │                 └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
       │    │                    └ WATAnnotation()
       │    └ 'Project_Gutenberg'
       └ WATAnnotation()

AttributeError: 'WATAnnotation' object has no attribute 'prior_prob'
2024-12-01 13:38:41.770 | INFO     | Core.Graph.PassageGraph:_build_graph:72 - Constructing graph finished
2024-12-01 13:40:13.696 | ERROR    | Core.Graph.PassageGraph:_build_graph:70 - Error building graph: 'Config' object has no attribute 'prior_prob'
Traceback (most recent call last):

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2270, in <module>
    main()
    └ <function main at 0x7c63e8fac7c0>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2252, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 29781, 'vm_type': None, 'client': None, 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': False, 'mu...
              │        └ <function PyDB.run at 0x7c63e8fab420>
              └ <__main__.PyDB object at 0x7c647b79e650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1563, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ '/home/yingli/GraphRAG/test_kgp.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x7c63e8fab4c0>
           └ <__main__.PyDB object at 0x7c647b79e650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ '/home/yingli/GraphRAG/test_kgp.py'
    │             └ <function execfile at 0x7c642012a340>
    └ <module '_pydev_bundle.pydev_imports' from '/home/yingli/.pycharm_helpers/pydev/_pydev_bundle/pydev_imports.py'>

  File "/home/yingli/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ '/home/yingli/GraphRAG/test_kgp.py'
                 └ 'from typing import Union, Any\n\nimport tiktoken\n\nfrom Core.Chunk.ChunkFactory import get_chunks\nfrom Core.Common.Utils i...

  File "/home/yingli/GraphRAG/test_kgp.py", line 38, in <module>
    asyncio.run(graph.build_graph(ordered_chunks))
    │       │   │     │           └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
    │       │   │     └ <function BaseGraph.build_graph at 0x7c63c116fa60>
    │       │   └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
    │       └ <function _patch_asyncio.<locals>.run at 0x7c63e8fd6d40>
    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           │    │                  └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
           │    └ <function _patch_loop.<locals>.run_until_complete at 0x7c63e8fd72e0>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
    │    └ <function _patch_loop.<locals>._run_once at 0x7c63e8fd7380>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7c6408779800>
    └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.__wakeup(<_GatheringFu...prior_prob'")>)>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 352, in __wakeup
    self.__step(exc)
    │           └ AttributeError("'Config' object has no attribute 'prior_prob'")
    └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 394, in step
    step_orig(task, exc)
    │         │     └ AttributeError("'Config' object has no attribute 'prior_prob'")
    │         └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
    └ <function Task.__step at 0x7c64087c5bc0>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 279, in __step
    result = coro.throw(exc)
             │    │     └ AttributeError("'Config' object has no attribute 'prior_prob'")
             │    └ <method 'throw' of 'coroutine' objects>
             └ <coroutine object BaseGraph.build_graph at 0x7c63c25b01e0>

  File "/home/yingli/GraphRAG/Core/Graph/BaseGraph.py", line 52, in build_graph
    await self._build_graph(chunks)
          │    │            └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
          │    └ <function PassageGraph._build_graph at 0x7c63bf34e7a0>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

> File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 65, in _build_graph
    results = await asyncio.gather(
                    │       └ <function gather at 0x7c64087c6480>
                    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 349, in __wakeup
    future.result()
    │      └ <method 'result' of '_asyncio.Future' objects>
    └ <_GatheringFuture finished exception=AttributeError("'Config' object has no attribute 'prior_prob'")>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             │    └ <method 'send' of 'coroutine' objects>
             └ <coroutine object PassageGraph._extract_node_relationship at 0x7c63bf307c40>

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 61, in _extract_node_relationship
    return await self._build_graph_from_wat(wat_annotations, chunk_key)
                 │    │                     │                └ 'chunk-d5cb63c91e4bea751bf090388c7859e9'
                 │    │                     └ [WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAnnotation(), WATAn...
                 │    └ <function PassageGraph._build_graph_from_wat at 0x7c63bf34ea20>
                 └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 103, in _build_graph_from_wat
    if wiki.wiki_title != '' and wiki.prior_prob > self.config.prior_prob:
       │    │                    │    │            │    └ Config(extra_fields=None, project_path='', project_name='', inc=False, reqa_file='', max_auto_summarize_code=0, git_reinit=Fa...
       │    │                    │    │            └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
       │    │                    │    └ 1.0
       │    │                    └ WATAnnotation()
       │    └ 'Project_Gutenberg'
       └ WATAnnotation()

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/site-packages/pydantic/main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')

AttributeError: 'Config' object has no attribute 'prior_prob'
2024-12-01 13:40:13.792 | INFO     | Core.Graph.PassageGraph:_build_graph:72 - Constructing graph finished
2024-12-01 13:41:26.275 | ERROR    | Core.Graph.PassageGraph:_build_graph:70 - Error building graph: PassageGraph.__passage_graph__() missing 1 required positional argument: 'chunk_list'
Traceback (most recent call last):

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2270, in <module>
    main()
    └ <function main at 0x78c074ba87c0>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2252, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 29781, 'vm_type': None, 'client': None, 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': False, 'mu...
              │        └ <function PyDB.run at 0x78c074ba7420>
              └ <__main__.PyDB object at 0x78c104cc2650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1563, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ '/home/yingli/GraphRAG/test_kgp.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x78c074ba74c0>
           └ <__main__.PyDB object at 0x78c104cc2650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ '/home/yingli/GraphRAG/test_kgp.py'
    │             └ <function execfile at 0x78c0abd26340>
    └ <module '_pydev_bundle.pydev_imports' from '/home/yingli/.pycharm_helpers/pydev/_pydev_bundle/pydev_imports.py'>

  File "/home/yingli/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ '/home/yingli/GraphRAG/test_kgp.py'
                 └ 'from typing import Union, Any\n\nimport tiktoken\n\nfrom Core.Chunk.ChunkFactory import get_chunks\nfrom Core.Common.Utils i...

  File "/home/yingli/GraphRAG/test_kgp.py", line 38, in <module>
    asyncio.run(graph.build_graph(ordered_chunks))
    │       │   │     │           └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
    │       │   │     └ <function BaseGraph.build_graph at 0x78c049b6fce0>
    │       │   └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
    │       └ <function _patch_asyncio.<locals>.run at 0x78c074bd2e80>
    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           │    │                  └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
           │    └ <function _patch_loop.<locals>.run_until_complete at 0x78c074bd3420>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
    │    └ <function _patch_loop.<locals>._run_once at 0x78c074bd34c0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x78c094375800>
    └ <Handle Task.__wakeup(<_GatheringFu...}, ...}, ...]>)>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.__wakeup(<_GatheringFu...}, ...}, ...]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.__wakeup(<_GatheringFu...}, ...}, ...]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.__wakeup(<_GatheringFu...}, ...}, ...]>)>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 360, in __wakeup
    self.__step()
    └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 394, in step
    step_orig(task, exc)
    │         │     └ None
    │         └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
    └ <function Task.__step at 0x78c0943c1bc0>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             │    └ <method 'send' of 'coroutine' objects>
             └ <coroutine object BaseGraph.build_graph at 0x78c04afb02b0>

  File "/home/yingli/GraphRAG/Core/Graph/BaseGraph.py", line 52, in build_graph
    await self._build_graph(chunks)
          │    │            └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
          │    └ <function PassageGraph._build_graph at 0x78c047d4aa20>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

> File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 68, in _build_graph
    await self.__passage_graph__(results)
          │    │                 └ [{'Project_Gutenberg': {'chunk-d5cb63c91e4bea751bf090388c7859e9'}, 'E-book': {'chunk-d5cb63c91e4bea751bf090388c7859e9'}, 'To_...
          │    └ <function PassageGraph.__passage_graph__ at 0x78c047d4aac0>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

TypeError: PassageGraph.__passage_graph__() missing 1 required positional argument: 'chunk_list'
2024-12-01 13:41:26.363 | INFO     | Core.Graph.PassageGraph:_build_graph:72 - Constructing graph finished
2024-12-01 13:43:43.684 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-d5cb63c91e4bea751bf090388c7859e9
2024-12-01 13:43:47.995 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-83b453141113eb22d088292ab927dab5
2024-12-01 13:43:51.913 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-3f91b711e91ce83668562edd142135a4
2024-12-01 13:43:55.966 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-90b2a67c265ac95538c8556696d41e85
2024-12-01 13:44:00.162 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-167195a2f3d31885e7de4ba99cafd363
2024-12-01 13:44:04.103 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-4bbeecd2c73ef0c2e77eb7b3bb64b5dc
2024-12-01 13:44:08.072 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-9b250b490516cb0f92c5f5f8736a341d
2024-12-01 13:44:12.008 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-c8616e24ddfb3bf6d00e8084b4b9c606
2024-12-01 13:44:16.183 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-aff6f422ee038e5b2ff9990f93363cdd
2024-12-01 13:44:19.051 | ERROR    | Core.Graph.PassageGraph:_build_graph:71 - Error building graph: Relationship.__init__() missing 1 required positional argument: 'source_id'
Traceback (most recent call last):

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2270, in <module>
    main()
    └ <function main at 0x7c0e2b5ac7c0>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2252, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 29781, 'vm_type': None, 'client': None, 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': False, 'mu...
              │        └ <function PyDB.run at 0x7c0e2b5ab420>
              └ <__main__.PyDB object at 0x7c0ebb6c6650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1563, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ '/home/yingli/GraphRAG/test_kgp.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x7c0e2b5ab4c0>
           └ <__main__.PyDB object at 0x7c0ebb6c6650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ '/home/yingli/GraphRAG/test_kgp.py'
    │             └ <function execfile at 0x7c0e6272a340>
    └ <module '_pydev_bundle.pydev_imports' from '/home/yingli/.pycharm_helpers/pydev/_pydev_bundle/pydev_imports.py'>

  File "/home/yingli/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ '/home/yingli/GraphRAG/test_kgp.py'
                 └ 'from typing import Union, Any\n\nimport tiktoken\n\nfrom Core.Chunk.ChunkFactory import get_chunks\nfrom Core.Common.Utils i...

  File "/home/yingli/GraphRAG/test_kgp.py", line 38, in <module>
    asyncio.run(graph.build_graph(ordered_chunks))
    │       │   │     │           └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
    │       │   │     └ <function BaseGraph.build_graph at 0x7c0e0176fb00>
    │       │   └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
    │       └ <function _patch_asyncio.<locals>.run at 0x7c0e2b5d6d40>
    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           │    │                  └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
           │    └ <function _patch_loop.<locals>.run_until_complete at 0x7c0e2b5d72e0>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
    │    └ <function _patch_loop.<locals>._run_once at 0x7c0e2b5d7380>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7c0e4ad79800>
    └ <Handle Task.__wakeup(<_GatheringFu...}, ...}, ...]>)>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.__wakeup(<_GatheringFu...}, ...}, ...]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.__wakeup(<_GatheringFu...}, ...}, ...]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.__wakeup(<_GatheringFu...}, ...}, ...]>)>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 360, in __wakeup
    self.__step()
    └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 394, in step
    step_orig(task, exc)
    │         │     └ None
    │         └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
    └ <function Task.__step at 0x7c0e4adc5bc0>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             │    └ <method 'send' of 'coroutine' objects>
             └ <coroutine object BaseGraph.build_graph at 0x7c0e02bb6670>

  File "/home/yingli/GraphRAG/Core/Graph/BaseGraph.py", line 52, in build_graph
    await self._build_graph(chunks)
          │    │            └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
          │    └ <function PassageGraph._build_graph at 0x7c0dff952840>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

> File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 69, in _build_graph
    await self.__passage_graph__(results, chunk_list)
          │    │                 │        └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
          │    │                 └ [{'Project_Gutenberg': {'chunk-d5cb63c91e4bea751bf090388c7859e9'}, 'E-book': {'chunk-d5cb63c91e4bea751bf090388c7859e9'}, 'To_...
          │    └ <function PassageGraph.__passage_graph__ at 0x7c0dff9528e0>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 93, in __passage_graph__
    edge_data = Relationship(src_id=src_id, tgt_id=tgt_id, relation_name=wiki_key)
                │                   │              │                     └ 'Illustration'
                │                   │              └ 'chunk-d5cb63c91e4bea751bf090388c7859e9'
                │                   └ 'chunk-83b453141113eb22d088292ab927dab5'
                └ <class 'Core.Schema.EntityRelation.Relationship'>

TypeError: Relationship.__init__() missing 1 required positional argument: 'source_id'
2024-12-01 13:44:19.139 | INFO     | Core.Graph.PassageGraph:_build_graph:73 - Constructing graph finished
2024-12-01 13:46:12.084 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-d5cb63c91e4bea751bf090388c7859e9
2024-12-01 13:46:16.135 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-83b453141113eb22d088292ab927dab5
2024-12-01 13:46:20.784 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-3f91b711e91ce83668562edd142135a4
2024-12-01 13:46:24.920 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-90b2a67c265ac95538c8556696d41e85
2024-12-01 13:46:28.909 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-167195a2f3d31885e7de4ba99cafd363
2024-12-01 13:46:33.101 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-4bbeecd2c73ef0c2e77eb7b3bb64b5dc
2024-12-01 13:46:37.454 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-9b250b490516cb0f92c5f5f8736a341d
2024-12-01 13:46:41.316 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-c8616e24ddfb3bf6d00e8084b4b9c606
2024-12-01 13:46:45.453 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-aff6f422ee038e5b2ff9990f93363cdd
2024-12-01 13:46:47.829 | ERROR    | Core.Graph.PassageGraph:_build_graph:71 - Error building graph: str.join() takes exactly one argument (2 given)
Traceback (most recent call last):

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2270, in <module>
    main()
    └ <function main at 0x7a795f5a47c0>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2252, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 29781, 'vm_type': None, 'client': None, 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': False, 'mu...
              │        └ <function PyDB.run at 0x7a795f5a3420>
              └ <__main__.PyDB object at 0x7a79f1f32650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1563, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ '/home/yingli/GraphRAG/test_kgp.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x7a795f5a34c0>
           └ <__main__.PyDB object at 0x7a79f1f32650>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ '/home/yingli/GraphRAG/test_kgp.py'
    │             └ <function execfile at 0x7a7996722340>
    └ <module '_pydev_bundle.pydev_imports' from '/home/yingli/.pycharm_helpers/pydev/_pydev_bundle/pydev_imports.py'>

  File "/home/yingli/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ '/home/yingli/GraphRAG/test_kgp.py'
                 └ 'from typing import Union, Any\n\nimport tiktoken\n\nfrom Core.Chunk.ChunkFactory import get_chunks\nfrom Core.Common.Utils i...

  File "/home/yingli/GraphRAG/test_kgp.py", line 38, in <module>
    asyncio.run(graph.build_graph(ordered_chunks))
    │       │   │     │           └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
    │       │   │     └ <function BaseGraph.build_graph at 0x7a7936567ba0>
    │       │   └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
    │       └ <function _patch_asyncio.<locals>.run at 0x7a795f5ced40>
    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           │    │                  └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
           │    └ <function _patch_loop.<locals>.run_until_complete at 0x7a795f5cf2e0>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
    │    └ <function _patch_loop.<locals>._run_once at 0x7a795f5cf380>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7a797ed71800>
    └ <Handle Task.__wakeup(<_GatheringFu...}, ...}, ...]>)>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.__wakeup(<_GatheringFu...}, ...}, ...]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.__wakeup(<_GatheringFu...}, ...}, ...]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.__wakeup(<_GatheringFu...}, ...}, ...]>)>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 360, in __wakeup
    self.__step()
    └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 394, in step
    step_orig(task, exc)
    │         │     └ None
    │         └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
    └ <function Task.__step at 0x7a797edbdbc0>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             │    └ <method 'send' of 'coroutine' objects>
             └ <coroutine object BaseGraph.build_graph at 0x7a79379af100>

  File "/home/yingli/GraphRAG/Core/Graph/BaseGraph.py", line 52, in build_graph
    await self._build_graph(chunks)
          │    │            └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
          │    └ <function PassageGraph._build_graph at 0x7a79347468e0>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

> File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 69, in _build_graph
    await self.__passage_graph__(results, chunk_list)
          │    │                 │        └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
          │    │                 └ [{'Project_Gutenberg': {'chunk-d5cb63c91e4bea751bf090388c7859e9'}, 'E-book': {'chunk-d5cb63c91e4bea751bf090388c7859e9'}, 'To_...
          │    └ <function PassageGraph.__passage_graph__ at 0x7a7934746980>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 94, in __passage_graph__
    source_id=GRAPH_FIELD_SEP.join(chunk1, chunk2))
              │               │    │       └ 'chunk-83b453141113eb22d088292ab927dab5'
              │               │    └ 'chunk-d5cb63c91e4bea751bf090388c7859e9'
              │               └ <method 'join' of 'str' objects>
              └ '<SEP>'

TypeError: str.join() takes exactly one argument (2 given)
2024-12-01 13:46:47.919 | INFO     | Core.Graph.PassageGraph:_build_graph:73 - Constructing graph finished
2024-12-01 13:48:16.061 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-d5cb63c91e4bea751bf090388c7859e9
2024-12-01 13:48:20.170 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-83b453141113eb22d088292ab927dab5
2024-12-01 13:48:24.024 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-3f91b711e91ce83668562edd142135a4
2024-12-01 13:48:28.047 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-90b2a67c265ac95538c8556696d41e85
2024-12-01 13:48:31.811 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-167195a2f3d31885e7de4ba99cafd363
2024-12-01 13:48:35.948 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-4bbeecd2c73ef0c2e77eb7b3bb64b5dc
2024-12-01 13:48:40.776 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-9b250b490516cb0f92c5f5f8736a341d
2024-12-01 13:48:44.860 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-c8616e24ddfb3bf6d00e8084b4b9c606
2024-12-01 13:48:49.074 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-aff6f422ee038e5b2ff9990f93363cdd
2024-12-01 13:50:15.772 | ERROR    | Core.Graph.PassageGraph:_build_graph:71 - Error building graph: expected string or buffer
Traceback (most recent call last):

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2270, in <module>
    main()
    └ <function main at 0x7f5cbedb07c0>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 2252, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              │        │   │                          └ False
              │        │   └ {'port': 29781, 'vm_type': None, 'client': None, 'server': False, 'DEBUG_RECORD_SOCKET_READS': False, 'multiproc': False, 'mu...
              │        └ <function PyDB.run at 0x7f5cbedaf420>
              └ <__main__.PyDB object at 0x7f5d46b76ad0>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1563, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           │    │     │          │               │            │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │    │     │          │               │            └ '/home/yingli/GraphRAG/test_kgp.py'
           │    │     │          │               └ None
           │    │     │          └ ''
           │    │     └ False
           │    └ <function PyDB._exec at 0x7f5cbedaf4c0>
           └ <__main__.PyDB object at 0x7f5d46b76ad0>

  File "/home/yingli/.pycharm_helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    │             │        │     │        └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
    │             │        └ '/home/yingli/GraphRAG/test_kgp.py'
    │             └ <function execfile at 0x7f5cf5f2e340>
    └ <module '_pydev_bundle.pydev_imports' from '/home/yingli/.pycharm_helpers/pydev/_pydev_bundle/pydev_imports.py'>

  File "/home/yingli/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
                 │              │              │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              │              └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
                 │              └ '/home/yingli/GraphRAG/test_kgp.py'
                 └ 'from typing import Union, Any\n\nimport tiktoken\n\nfrom Core.Chunk.ChunkFactory import get_chunks\nfrom Core.Common.Utils i...

  File "/home/yingli/GraphRAG/test_kgp.py", line 38, in <module>
    asyncio.run(graph.build_graph(ordered_chunks))
    │       │   │     │           └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
    │       │   │     └ <function BaseGraph.build_graph at 0x7f5c94373ba0>
    │       │   └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
    │       └ <function _patch_asyncio.<locals>.run at 0x7f5cbeddad40>
    └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           │    │                  └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
           │    └ <function _patch_loop.<locals>.run_until_complete at 0x7f5cbeddb2e0>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 234, in run_until_complete
    self._run_once()
    │    └ <function _patch_loop.<locals>._run_once at 0x7f5cbeddb380>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 286, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f5ce057d800>
    └ <Handle Task.__wakeup(<_GatheringFu...g or buffer')>)>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.__wakeup(<_GatheringFu...g or buffer')>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.__wakeup(<_GatheringFu...g or buffer')>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.__wakeup(<_GatheringFu...g or buffer')>)>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 352, in __wakeup
    self.__step(exc)
    │           └ TypeError('expected string or buffer')
    └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>

  File "/home/yingli/.pycharm_helpers/pydevd_asyncio/pydevd_nest_asyncio.py", line 394, in step
    step_orig(task, exc)
    │         │     └ TypeError('expected string or buffer')
    │         └ <Task pending name='Task-2' coro=<BaseGraph.build_graph() running at /home/yingli/GraphRAG/Core/Graph/BaseGraph.py:52>>
    └ <function Task.__step at 0x7f5ce05c9bc0>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 279, in __step
    result = coro.throw(exc)
             │    │     └ TypeError('expected string or buffer')
             │    └ <method 'throw' of 'coroutine' objects>
             └ <coroutine object BaseGraph.build_graph at 0x7f5c957b8380>

  File "/home/yingli/GraphRAG/Core/Graph/BaseGraph.py", line 52, in build_graph
    await self._build_graph(chunks)
          │    │            └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
          │    └ <function PassageGraph._build_graph at 0x7f5c925528e0>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

> File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 69, in _build_graph
    await self.__passage_graph__(results, chunk_list)
          │    │                 │        └ [('chunk-d5cb63c91e4bea751bf090388c7859e9', TextChunk()), ('chunk-83b453141113eb22d088292ab927dab5', TextChunk()), ('chunk-3f...
          │    │                 └ [{'Project_Gutenberg': {'chunk-d5cb63c91e4bea751bf090388c7859e9'}, 'E-book': {'chunk-d5cb63c91e4bea751bf090388c7859e9'}, 'To_...
          │    └ <function PassageGraph.__passage_graph__ at 0x7f5c92552980>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

  File "/home/yingli/GraphRAG/Core/Graph/PassageGraph.py", line 98, in __passage_graph__
    await asyncio.gather(*[self._merge_nodes_then_upsert(k, v) for k, v in maybe_nodes.items()])
          │       │        │    │                        │  │      │  │    │           └ <method 'items' of 'dict' objects>
          │       │        │    │                        │  │      │  │    └ defaultdict(<class 'list'>, {'chunk-d5cb63c91e4bea751bf090388c7859e9': [Entity()], 'chunk-83b453141113eb22d088292ab927dab5': ...
          │       │        │    │                        │  │      │  └ {'chunk-aff6f422ee038e5b2ff9990f93363cdd'}
          │       │        │    │                        │  │      └ 'Tile'
          │       │        │    │                        │  └ {'chunk-aff6f422ee038e5b2ff9990f93363cdd'}
          │       │        │    │                        └ 'Tile'
          │       │        │    └ <function BaseGraph._merge_nodes_then_upsert at 0x7f5c9438c720>
          │       │        └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...
          │       └ <function gather at 0x7f5ce05ca480>
          └ <module 'asyncio' from '/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/__init__.py'>

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 349, in __wakeup
    future.result()
    │      └ <method 'result' of '_asyncio.Future' objects>
    └ <_GatheringFuture finished exception=TypeError('expected string or buffer')>
  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             │    └ <method 'send' of 'coroutine' objects>
             └ <coroutine object BaseGraph._merge_nodes_then_upsert at 0x7f5c925d82e0>

  File "/home/yingli/GraphRAG/Core/Graph/BaseGraph.py", line 96, in _merge_nodes_then_upsert
    await self._handle_entity_relation_summary(entity_name, merge_description)
          │    │                               │            └ []
          │    │                               └ 'chunk-d5cb63c91e4bea751bf090388c7859e9'
          │    └ <function BaseGraph._handle_entity_relation_summary at 0x7f5c9438cae0>
          └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

  File "/home/yingli/GraphRAG/Core/Graph/BaseGraph.py", line 257, in _handle_entity_relation_summary
    tokens = self.ENCODER.encode(description)
             │    │       │      └ []
             │    │       └ <function Encoding.encode at 0x7f5d4e6137e0>
             │    └ <Encoding 'cl100k_base'>
             └ PassageGraph(private_context=None, private_config=None, private_llm=None, chunks=None, llm_name_or_type=None, working_memory=...

  File "/home/yingli/anaconda3/envs/graphrag/lib/python3.11/site-packages/tiktoken/core.py", line 116, in encode
    if match := _special_token_regex(disallowed_special).search(text):
                │                    │                          └ []
                │                    └ frozenset({'<|endoftext|>', '<|fim_suffix|>', '<|fim_middle|>', '<|endofprompt|>', '<|fim_prefix|>'})
                └ <functools._lru_cache_wrapper object at 0x7f5cc37ebd70>

TypeError: expected string or buffer
2024-12-01 13:50:15.873 | INFO     | Core.Graph.PassageGraph:_build_graph:73 - Constructing graph finished
2024-12-01 13:50:57.187 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-d5cb63c91e4bea751bf090388c7859e9
2024-12-01 13:51:01.362 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-83b453141113eb22d088292ab927dab5
2024-12-01 13:51:05.021 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-3f91b711e91ce83668562edd142135a4
2024-12-01 13:51:09.146 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-90b2a67c265ac95538c8556696d41e85
2024-12-01 13:51:13.422 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-167195a2f3d31885e7de4ba99cafd363
2024-12-01 13:51:17.514 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-4bbeecd2c73ef0c2e77eb7b3bb64b5dc
2024-12-01 13:51:21.397 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-9b250b490516cb0f92c5f5f8736a341d
2024-12-01 13:51:25.161 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-c8616e24ddfb3bf6d00e8084b4b9c606
2024-12-01 13:51:29.532 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-aff6f422ee038e5b2ff9990f93363cdd
2024-12-01 13:52:09.192 | INFO     | Core.Graph.PassageGraph:_build_graph:73 - Constructing graph finished
2024-12-01 13:52:29.481 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-d5cb63c91e4bea751bf090388c7859e9
2024-12-01 13:52:33.653 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-83b453141113eb22d088292ab927dab5
2024-12-01 13:52:37.559 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-3f91b711e91ce83668562edd142135a4
2024-12-01 13:52:41.718 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-90b2a67c265ac95538c8556696d41e85
2024-12-01 13:52:46.204 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-167195a2f3d31885e7de4ba99cafd363
2024-12-01 13:52:49.724 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-4bbeecd2c73ef0c2e77eb7b3bb64b5dc
2024-12-01 13:52:54.140 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-9b250b490516cb0f92c5f5f8736a341d
2024-12-01 13:52:58.212 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-c8616e24ddfb3bf6d00e8084b4b9c606
2024-12-01 13:53:02.308 | INFO     | Core.Graph.PassageGraph:_extract_node_relationship:60 - Linking Entity by WAT system for chunk chunk-aff6f422ee038e5b2ff9990f93363cdd
2024-12-01 13:53:33.077 | INFO     | Core.Graph.PassageGraph:_build_graph:73 - Constructing graph finished
